[package]
name = "kmpeek"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.3"
rdev = "0.5.2"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
three-d = "0.15.0"
three-d-asset = "0.5.0"
