[package]
name = "kmpeek"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.10.1"
bevy_egui = "0.20.3"
bevy_infinite_grid = "0.7.0"
bytemuck = "1.13.1"
byteorder = "1.4.3"
futures-lite = "1.13.0"
num-traits = "0.2.15"
rfd = "0.11.4"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies
[profile.dev.package."*"]
opt-level = 3

[profile.release]
opt-level = 3
lto = true
strip = true
codegen-units = 1
