[package]
name = "kmpeek"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.11", default-features = false, features = [
    "bevy_render",
    "bevy_winit",
    "multi-threaded",
    "filesystem_watcher",
    "tonemapping_luts",
    "ktx2",
    "zstd",
] }
bevy_egui = "0.21.0"
bevy_infinite_grid = { git = "https://github.com/Hibyehello/bevy_infinite_grid.git" }
# using this branch until bevy_mod_picking for bevy 0.11 comes out
bevy_mod_picking = { git = "https://github.com/bardt/bevy_mod_picking", branch = "bevy_0.11" }
bevy_more_shapes = { git = "https://github.com/Hibyehello/bevy_more_shapes.git" }
bytemuck = "1.13.1"
byteorder = "1.4.3"
egui_dock = "0.6.3"
# egui_dock = { git = "https://github.com/Vickerinox/egui_dock", branch = "window-dock/undocking" }
num-traits = "0.2.15"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
strum = "0.25.0"
strum_macros = "0.25.1"

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies
[profile.dev.package."*"]
opt-level = 3

[profile.release]
opt-level = 3
lto = true
strip = true
codegen-units = 1
