[package]
name = "kmpeek"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.11", default-features = false, features = [
    "bevy_render",
    "bevy_asset",
] }
bevy_egui = "0.21.0"
bevy_infinite_grid = { git = "https://github.com/Hibyehello/bevy_infinite_grid.git" }
bevy_more_shapes = { git = "https://github.com/Hibyehello/bevy_more_shapes.git" }
bytemuck = "1.13.1"
byteorder = "1.4.3"
num-traits = "0.2.15"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies
[profile.dev.package."*"]
opt-level = 3

[profile.release]
opt-level = 3
lto = true
strip = true
codegen-units = 1
